azure-pipelines-jdl-ms-keycloak.yml, test-integration/jdl-scripts/25-tests-e2e-docker-compose.sh
Fixes #6 
@pascalgrimaud this pipeline tests 10 jobs at the same time so it takes only one slot for the daily builds schedule.
=> Keycloak daily builds

README.md
Added badges and configured azure pipeline to add new builds
=> Readmebadges

test-integration/scripts/00-init-env.sh
@pascalgrimaud : I've overlooked a small detail in #19. Without this #19 will not work. Also, after this is merged, is it possible to restart the Java 8 build rather than waiting until tomorrow. Sorry about that. :cry:
=> Correct Mistake in Pull Request #19

README.md
sorry :v
I forgot them in last PR
=> Fixed missing links for readme.md

.travis.yml, azure-pipelines.yml, azure-template-plus.yml, azure-template-windows.yml, azure-template.yml
Related to https://github.com/jhipster/generator-jhipster/pull/10707
=> update Node version to v12.13.0

.travis.yml, azure-pipelines.yml, azure-template-plus.yml, azure-template-windows.yml, azure-template.yml
Related with https://github.com/jhipster/generator-jhipster/pull/11067
=> Update node to version 12.14.0 LTS

azure-pipelines-ngx-gradle-nosql.yml, azure-pipelines-ngx-maven-nosql.yml, test-integration/samples/gradle-ngx-neo4j/.yo-rc.json, test-integration/samples/ngx-neo4j/.yo-rc.json
I hope the setup is correct. Just testing default config for neo4j with gradle and maven within the nosql tests
=> Add neo4j support

.github/workflows/github-actions-jdl-app-caffeine-mariadb.yaml, .github/workflows/github-actions-jdl-app-caffeine-mysql.yaml, .github/workflows/github-actions-jdl-app-ehcache-mariadb.yaml, .github/workflows/github-actions-jdl-app-ehcache-mysql.yaml, .github/workflows/github-actions-jdl-app-hazelcast-mariadb.yaml, .github/workflows/github-actions-jdl-app-hazelcast-mysql.yaml, .github/workflows/github-actions-jdl-app-infinispan-mariadb.yaml, .github/workflows/github-actions-jdl-app-infinispan-mysql.yaml, .github/workflows/github-actions-jdl-app-keycloak.yaml, .github/workflows/github-actions-jdl-app-memcached-mariadb.yaml, .github/workflows/github-actions-jdl-app-memcached-mysql.yaml, .github/workflows/github-actions-jdl-app-no-mariadb.yaml, .github/workflows/github-actions-jdl-app-no-mysql.yaml, .github/workflows/github-actions-jdl-app-redis-mariadb.yaml, .github/workflows/github-actions-jdl-app-redis-mysql.yaml, test-integration/jdl-scripts/00-init-env.sh, test-integration/jdl-scripts/28-deploy-with-kubernetes.sh
Adding JDL Based daily pipelines but on GitHub Actions
(See [#11391](https://github.com/jhipster/generator-jhipster/issues/11391))
=> migration jdl to github actions

.github/workflows/windows.yaml
This enables and fixes all issues in related to the Windows build.
Fixes #48
=> Fix for Windows Build

.github/workflows/neo4j.yaml
This enabled neo4j daily builds again. mvn verify/gradle check now works as expected
=> enable neo4j daily build again

.github/workflows/couchbase.yaml
This changes the cron of Couchbase for testing as discussed in; https://github.com/testcontainers/testcontainers-java/issues/1453#issuecomment-616222321
cc: @hipster-labs/developers
=> Change Cron of Couchbase to run every 30 mins for Testing

.github/workflows/couchbase.yaml
Reverts hipster-labs/jhipster-daily-builds#52
=> Revert "Change Cron of Couchbase to run every 30 mins for Testing"

.github/workflows/neo4j.yaml, test-integration/samples/webflux-neo4j/.yo-rc.json
=> add reactive neo4j build to matrix

test-integration/jdl-scripts/25-tests-e2e-docker-compose.sh, test-integration/jdl-scripts/29-tests-e2e-kubernetes.sh
=> changed command for running e2e to npm run e2e:headless

test-integration/jdl-scripts/13-replace-version-generated-project.sh
Related to https://github.com/jhipster/generator-jhipster/pull/12559
=> Fix replace version script for JDL

.github/workflows/windows.yaml
Fix https://github.com/hipster-labs/jhipster-daily-builds/issues/59
=> Disable Kafka builds with Windows

.github/workflows/jdl-ms-redis-mysql.yaml
Related to https://github.com/hipster-labs/jhipster-daily-builds/issues/72
=> Test workflow_dispatch

.github/workflows/ngx-gradle-sql.yaml, .github/workflows/ngx-maven-sql.yaml, .github/workflows/react-gradle-sql.yaml, .github/workflows/react-maven-sql.yaml, .github/workflows/vue-gradle-sql.yaml, .github/workflows/vue-maven-sql.yaml, README.md
Minor improvement:
- when searching builds: https://github.com/hipster-labs/jhipster-daily-builds/actions?query=workflow%3A%22Angular+Maven%22
- it's to avoid having Angular Maven and Angular Maven NoSQL in the list
=> Add SQL in build name

.github/workflows/neo4j.yaml
following https://github.com/hipster-labs/jhipster-daily-builds/pull/79
=> Use main branch for Neo4j build

.github/workflows/ngx-maven-sql.yaml, .github/workflows/react-maven-sql.yaml, .github/workflows/vue-maven-sql.yaml
Fix https://github.com/hipster-labs/jhipster-daily-builds/pull/81#issuecomment-761545881
=> Fix schedule with manual parameters

.github/workflows/monolith-oauth2.yaml
@pascalgrimaud Should we add Vue to `monolith-oauth2.yml`?
=> Use sqllight for monolith oauth jobs

.github/workflows/no-database.yaml
Similar to https://github.com/hipster-labs/jhipster-daily-builds/pull/85
=> Add inputs to No Database builds

test-integration/samples/gradle-ms-ngx-gateway-consul-oauth2/.yo-rc.json, test-integration/samples/gradle-ms-ngx-gateway-eureka-oauth2-nodb/.yo-rc.json, test-integration/samples/gradle-ms-ngx-gateway-eureka-oauth2/.yo-rc.json, test-integration/samples/gradle-ms-ngx-gateway-eureka/.yo-rc.json, test-integration/samples/ms-ngx-gateway-consul-oauth2/.yo-rc.json, test-integration/samples/ms-ngx-gateway-consul/.yo-rc.json, test-integration/samples/ms-ngx-gateway-eureka-oauth2-nodb/.yo-rc.json, test-integration/samples/ms-ngx-gateway-eureka-oauth2/.yo-rc.json, test-integration/samples/ms-ngx-gateway-eureka/.yo-rc.json
Related to https://github.com/jhipster/generator-jhipster/issues/13855
=> Force reactive for all Gateway

.github/workflows/ms-jwt.yaml, .github/workflows/ms-oauth2.yaml, .github/workflows/windows.yaml
related to https://github.com/jhipster/generator-jhipster/issues/13855
=> Change entities to sqllight for gateways

test-integration/jdl-samples/templates/microservice-demo.jdl.ejs
Depends on https://github.com/jhipster/generator-jhipster/pull/14013
Related to https://github.com/jhipster/generator-jhipster/issues/13855
=> Change Docker Compose configuration from Zuul to SpringCloudGateway

test-integration/jdl-samples/templates/microservice-demo.jdl.ejs
Following https://github.com/jhipster/generator-jhipster/pull/14202
Related to https://github.com/jhipster/generator-jhipster/issues/14199
=> Rename size to productSize, as size is reserved keywords

.github/workflows/couchbase.yml, .github/workflows/elasticsearch.yaml, .github/workflows/monolith-oauth2.yaml, .github/workflows/ms-jwt.yaml, .github/workflows/ms-oauth2.yaml, .github/workflows/neo4j.yaml, .github/workflows/ngx-gradle-nosql.yaml, .github/workflows/ngx-gradle-sql.yaml, .github/workflows/ngx-maven-nosql.yaml, .github/workflows/ngx-maven-sql.yaml, .github/workflows/no-database.yaml, .github/workflows/react-gradle-nosql.yaml, .github/workflows/react-gradle-sql.yaml, .github/workflows/react-maven-nosql.yaml, .github/workflows/react-maven-sql.yaml, .github/workflows/vue-gradle-nosql.yaml, .github/workflows/vue-gradle-sql.yaml, .github/workflows/vue-maven-nosql.yaml, .github/workflows/vue-maven-sql.yaml, .github/workflows/windows.yaml
@pascalgrimaud use same Node version in all forkflows
=> Update node version to 14.15.5

.github/workflows/couchbase.yml, .github/workflows/elasticsearch.yaml, .github/workflows/jdl-broken-config.yaml, .github/workflows/jdl-consul-gradle-jwt.yaml, .github/workflows/jdl-consul-gradle-oauth2.yaml, .github/workflows/jdl-consul-maven-jwt.yaml, .github/workflows/jdl-consul-maven-oauth2.yaml, .github/workflows/jdl-eureka-gradle-jwt.yaml, .github/workflows/jdl-eureka-gradle-oauth2.yaml, .github/workflows/jdl-eureka-maven-jwt.yaml, .github/workflows/jdl-eureka-maven-oauth2.yaml, .github/workflows/monolith-oauth2.yaml, .github/workflows/ms-jwt.yaml, .github/workflows/ms-oauth2.yaml, .github/workflows/neo4j.yaml, .github/workflows/ngx-gradle-nosql.yaml, .github/workflows/ngx-gradle-sql.yaml, .github/workflows/ngx-maven-nosql.yaml, .github/workflows/ngx-maven-sql.yaml, .github/workflows/no-database.yaml, .github/workflows/react-gradle-nosql.yaml, .github/workflows/react-gradle-sql.yaml, .github/workflows/react-maven-nosql.yaml, .github/workflows/react-maven-sql.yaml, .github/workflows/vue-gradle-nosql.yaml, .github/workflows/vue-gradle-sql.yaml, .github/workflows/vue-maven-nosql.yaml, .github/workflows/vue-maven-sql.yaml, .github/workflows/windows.yaml
Related with https://github.com/jhipster/generator-jhipster/issues/14304
=> Update Nodejs version to 14.16.0

.github/workflows/couchbase.yml, .github/workflows/elasticsearch.yaml, .github/workflows/jdl-broken-config.yaml, .github/workflows/jdl-consul-gradle-jwt.yaml, .github/workflows/jdl-consul-gradle-oauth2.yaml, .github/workflows/jdl-consul-maven-jwt.yaml, .github/workflows/jdl-consul-maven-oauth2.yaml, .github/workflows/jdl-eureka-gradle-jwt.yaml, .github/workflows/jdl-eureka-gradle-oauth2.yaml, .github/workflows/jdl-eureka-maven-jwt.yaml, .github/workflows/jdl-eureka-maven-oauth2.yaml, .github/workflows/monolith-oauth2.yaml, .github/workflows/ms-jwt.yaml, .github/workflows/ms-oauth2.yaml, .github/workflows/neo4j.yaml, .github/workflows/ngx-gradle-nosql.yaml, .github/workflows/ngx-gradle-sql.yaml, .github/workflows/ngx-maven-nosql.yaml, .github/workflows/ngx-maven-sql.yaml, .github/workflows/no-database.yaml, .github/workflows/react-gradle-nosql.yaml, .github/workflows/react-gradle-sql.yaml, .github/workflows/react-maven-nosql.yaml, .github/workflows/react-maven-sql.yaml, .github/workflows/vue-gradle-nosql.yaml, .github/workflows/vue-gradle-sql.yaml, .github/workflows/vue-maven-nosql.yaml, .github/workflows/vue-maven-sql.yaml, .github/workflows/windows.yaml
Related with https://github.com/jhipster/generator-jhipster/pull/14598
=> Bump actions/setup-java from v1 to v2

.github/workflows/couchbase.yml, .github/workflows/docker-image.yaml, .github/workflows/elasticsearch.yaml, .github/workflows/jdl-broken-config.yaml, .github/workflows/jdl-consul-gradle-jwt.yaml, .github/workflows/jdl-consul-gradle-oauth2.yaml, .github/workflows/jdl-consul-maven-jwt.yaml, .github/workflows/jdl-consul-maven-oauth2.yaml, .github/workflows/jdl-eureka-gradle-jwt.yaml, .github/workflows/jdl-eureka-gradle-oauth2.yaml, .github/workflows/jdl-eureka-maven-jwt.yaml, .github/workflows/jdl-eureka-maven-oauth2.yaml, .github/workflows/monolith-oauth2.yaml, .github/workflows/ms-jwt.yaml, .github/workflows/ms-oauth2.yaml, .github/workflows/neo4j.yaml, .github/workflows/ngx-gradle-nosql.yaml, .github/workflows/ngx-gradle-sql.yaml, .github/workflows/ngx-maven-nosql.yaml, .github/workflows/ngx-maven-sql.yaml, .github/workflows/no-database.yaml, .github/workflows/react-gradle-nosql.yaml, .github/workflows/react-gradle-sql.yaml, .github/workflows/react-maven-nosql.yaml, .github/workflows/react-maven-sql.yaml, .github/workflows/vue-gradle-nosql.yaml, .github/workflows/vue-gradle-sql.yaml, .github/workflows/vue-maven-nosql.yaml, .github/workflows/vue-maven-sql.yaml, .github/workflows/windows.yaml
Closes https://github.com/jhipster/generator-jhipster/issues/15205
=> Group and cancel outdated builds.

.github/workflows/couchbase.yml, .github/workflows/elasticsearch.yaml, .github/workflows/jdl-broken-config.yaml, .github/workflows/jdl-consul-gradle-jwt.yaml, .github/workflows/jdl-consul-gradle-oauth2.yaml, .github/workflows/jdl-consul-maven-jwt.yaml, .github/workflows/jdl-consul-maven-oauth2.yaml, .github/workflows/jdl-eureka-gradle-jwt.yaml, .github/workflows/jdl-eureka-gradle-oauth2.yaml, .github/workflows/jdl-eureka-maven-jwt.yaml, .github/workflows/jdl-eureka-maven-oauth2.yaml, .github/workflows/monolith-oauth2.yaml, .github/workflows/ms-jwt.yaml, .github/workflows/ms-oauth2.yaml, .github/workflows/neo4j.yaml, .github/workflows/ngx-gradle-nosql.yaml, .github/workflows/ngx-gradle-sql.yaml, .github/workflows/ngx-maven-nosql.yaml, .github/workflows/ngx-maven-sql.yaml, .github/workflows/no-database.yaml, .github/workflows/react-gradle-nosql.yaml, .github/workflows/react-gradle-sql.yaml, .github/workflows/react-maven-nosql.yaml, .github/workflows/react-maven-sql.yaml, .github/workflows/vue-gradle-nosql.yaml, .github/workflows/vue-gradle-sql.yaml, .github/workflows/vue-maven-nosql.yaml, .github/workflows/vue-maven-sql.yaml, .github/workflows/windows.yaml
related to https://github.com/jhipster/generator-jhipster/pull/18776#issuecomment-1142167225
=> update ci using npm commands instead of script

.github/workflows/windows.yaml
Related to https://github.com/jhipster/generator-jhipster/issues/19225.
=> fix windows ci

test-integration/scripts/26-tests-docker.sh
Should fix docker publish workflow.
=> adjust sample name.

.github/workflows/neo4j.yaml
Reverts hipster-labs/jhipster-daily-builds#142
=> Revert "Change cron for neo4j build to 1st day of month"

.github/workflows/no-database.yaml
Reverts hipster-labs/jhipster-daily-builds#143
=> Revert "Change cron for no-database builds to 1st day of month"

.github/workflows/windows.yaml
Reverts hipster-labs/jhipster-daily-builds#141
=> Revert "Change cron for windows build to 1st day of month"

test-integration/jdl-scripts/12-generate-project.sh, test-integration/jdl-scripts/26-tests-docker.sh, test-integration/scripts/26-tests-docker.sh
Related to https://github.com/jhipster/generator-jhipster/pull/23393.
=> drop --with-entities option

.github/dependabot.yml, .github/workflows/cache.yml, .github/workflows/couchbase.yml, .github/workflows/elasticsearch.yaml, .github/workflows/monolith-oauth2.yaml, .github/workflows/ms-jwt.yaml, .github/workflows/ms-oauth2.yaml, .github/workflows/neo4j.yaml, .github/workflows/ng-gradle-nosql.yaml, .github/workflows/ng-gradle-sql.yaml, .github/workflows/ng-maven-nosql.yaml, .github/workflows/ng-maven-sql.yaml, .github/workflows/no-database.yaml, .github/workflows/react-gradle-nosql.yaml, .github/workflows/react-gradle-sql.yaml, .github/workflows/react-maven-nosql.yaml, .github/workflows/react-maven-sql.yaml, .github/workflows/vue-gradle-nosql.yaml, .github/workflows/vue-gradle-sql.yaml, .github/workflows/vue-maven-nosql.yaml, .github/workflows/vue-maven-sql.yaml
Depends on https://github.com/jhipster/generator-jhipster/pull/26176
=> Jhipster actions

.github/workflows/windows.yaml
generator-jhipster's jit seems to not work on windows.
Use old approach to generate sample.
Fixes https://github.com/jhipster/generator-jhipster/issues/24135
=> migrate windows workflow to jhipster/actions
